### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by smups** [kanitsharma/gruber-dark-vscode#1]
Hi,

I noticed that quite a lot of the theme code in this repo was copied from my gruber theme [gruber fruity](https://github.com/smups/gruberfruity), specifically the lemon-dark variant.

There's nothing wrong with that of course, but I have released my code under the GPLv3, and you have redistributed it under an MIT license. This is not allowed according to the license under which I published my code, [see for instance this MIT license FAQ](https://www.tawesoft.co.uk/kb/article/mit-license-faq).

Please remove my code from your repo, or change the license of your additions to the GPL as well (I prefer the second one of course!). See section 8 of the GPL for more info.

Also, it'd be nice to get some credit, like a small notice or something that you used some of my code (this is not really required by the license, but would be nice of you :) )

**Comment by kanitsharma** [comment]
Hey @smups,

I want to apologize for any inconvenience caused. I will gladly update the license and give you proper credit for your theme. I must clarify that I used your theme extensively and created/modded this theme solely for my personal use. There was never any ill intent involved.
